name: define theme preset
permissions: read-all

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'packages/libs/themes-preset/src/tokens/**'

env:
  NX_NON_NATIVE_HASHER: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preset:
    name: define theme preset
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install --include=optional
      - run: npm run preset:ci